services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: unless-stopped

    environment:
      POSTGRES_DB: restaurant_database
      POSTGRES_USER: masterchief
      POSTGRES_PASSWORD: 1234

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: